# This file was automagically generated by mbed.org. For more information,
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

GCC_BIN =
PROJECT = BLE_UARTConsole
OBJECTS = ./nRF51822/nordic/bootloader_dfu/dfu_app_handler.o ./nRF51822/nordic/bootloader_dfu/bootloader_util_arm.o ./nRF51822/nordic/app_common/app_scheduler.o ./nRF51822/nordic/app_common/hci_mem_pool.o ./nRF51822/nordic/app_common/app_gpiote.o ./main.o ./nRF51822/nRF51Gap.o ./nRF51822/nRF51822n.o ./nRF51822/nRF51GattServer.o ./nRF51822/nordic/softdevice_handler.o ./nRF51822/nordic/app_common/crc16.o ./nRF51822/nordic/app_common/pstorage.o ./nRF51822/nordic/ble/ble_bondmngr.o ./nRF51822/nordic/ble/ble_debug_assert_handler.o ./nRF51822/nordic/ble/ble_advdata_parser.o ./nRF51822/nordic/ble/ble_conn_params.o ./nRF51822/nordic/ble/ble_error_log.o ./nRF51822/nordic/ble/ble_advdata.o ./nRF51822/nordic/ble/ble_services/ble_srv_common.o ./nRF51822/btle/btle_gap.o ./nRF51822/btle/btle_advertising.o ./nRF51822/btle/btle.o ./nRF51822/btle/custom/custom_helper.o ./BLE_API/services/UARTService.o ./BLE_API/services/DFUService.o ./BLE_API/common/GattService.o ./BLE_API/common/GapAdvertisingData.o ./BLE_API/common/GapAdvertisingParams.o ./BLE_API/common/BLEDevice.o ./BLE_API/common/UUID.o 
SYS_OBJECTS = ./mbed/TARGET_ARCH_BLE/TOOLCHAIN_GCC_ARM/cmsis_nvic.o ./mbed/TARGET_ARCH_BLE/TOOLCHAIN_GCC_ARM/startup_NRF51822.o ./mbed/TARGET_ARCH_BLE/TOOLCHAIN_GCC_ARM/system_nrf51822.o ./mbed/TARGET_ARCH_BLE/TOOLCHAIN_GCC_ARM/board.o ./mbed/TARGET_ARCH_BLE/TOOLCHAIN_GCC_ARM/retarget.o 
INCLUDE_PATHS = -I. -I./nRF51822 -I./nRF51822/nordic -I./nRF51822/nordic/nrf-sdk -I./nRF51822/nordic/nrf-sdk/s110 -I./nRF51822/nordic/nrf-sdk/bootloader_dfu -I./nRF51822/nordic/nrf-sdk/app_common -I./nRF51822/nordic/nrf-sdk/sd_common -I./nRF51822/nordic/nrf-sdk/ble -I./nRF51822/nordic/nrf-sdk/ble/device_manager -I./nRF51822/nordic/nrf-sdk/ble/ble_services -I./nRF51822/nordic/bootloader_dfu -I./nRF51822/nordic/app_common -I./nRF51822/nordic/ble -I./nRF51822/nordic/ble/ble_services -I./nRF51822/common -I./nRF51822/btle -I./nRF51822/btle/custom -I./mbed -I./mbed/TARGET_ARCH_BLE -I./mbed/TARGET_ARCH_BLE/TARGET_NORDIC -I./mbed/TARGET_ARCH_BLE/TARGET_NORDIC/TARGET_MCU_NRF51822 -I./mbed/TARGET_ARCH_BLE/TARGET_NORDIC/TARGET_MCU_NRF51822/TARGET_ARCH_BLE -I./mbed/TARGET_ARCH_BLE/TARGET_NORDIC/TARGET_MCU_NRF51822/Lib -I./mbed/TARGET_ARCH_BLE/TARGET_NORDIC/TARGET_MCU_NRF51822/Lib/nrf-sdk -I./mbed/TARGET_ARCH_BLE/TARGET_NORDIC/TARGET_MCU_NRF51822/Lib/nrf-sdk/app_common -I./mbed/TARGET_ARCH_BLE/TARGET_NORDIC/TARGET_MCU_NRF51822/Lib/nrf-sdk/sd_common -I./mbed/TARGET_ARCH_BLE/TARGET_NORDIC/TARGET_MCU_NRF51822/Lib/s110_nrf51822_7_0_0 -I./mbed/TARGET_ARCH_BLE/TARGET_NORDIC/TARGET_MCU_NRF51822/Lib/s110_nrf51822_7_0_0/s110_nrf51822_7.0.0_API -I./mbed/TARGET_ARCH_BLE/TARGET_NORDIC/TARGET_MCU_NRF51822/Lib/s110_nrf51822_7_0_0/s110_nrf51822_7.0.0_API/include -I./mbed/TARGET_ARCH_BLE/TOOLCHAIN_GCC_ARM -I./BLE_API -I./BLE_API/services -I./BLE_API/common -I./BLE_API/public 
LIBRARY_PATHS = -L./mbed/TARGET_ARCH_BLE/TOOLCHAIN_GCC_ARM 
LIBRARIES = -lmbed 
LINKER_SCRIPT = ./mbed/TARGET_ARCH_BLE/TOOLCHAIN_GCC_ARM/NRF51822.ld
SOFTDEVICE = mbed/TARGET_ARCH_BLE/TARGET_NORDIC/TARGET_MCU_NRF51822/Lib/s110_nrf51822_7_0_0/s110_nrf51822_7.0.0_softdevice.hex

###############################################################################
AS      = $(GCC_BIN)arm-none-eabi-as
CC      = $(GCC_BIN)arm-none-eabi-gcc
CPP     = $(GCC_BIN)arm-none-eabi-g++
LD      = $(GCC_BIN)arm-none-eabi-gcc
OBJCOPY = $(GCC_BIN)arm-none-eabi-objcopy
SREC_CAT = srec_cat

CPU = -mcpu=cortex-m0 -mthumb
CC_FLAGS = $(CPU) -c -g -fno-common -fmessage-length=0 -Wall -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer
CC_SYMBOLS = -DTARGET_ARCH_BLE -DTARGET_M0 -DTARGET_NORDIC -DTARGET_MCU_NRF51822 -DTARGET_MCU_NORDIC_16K -DTOOLCHAIN_GCC_ARM -DTOOLCHAIN_GCC -D__CORTEX_M0 -DARM_MATH_CM0 -DMBED_BUILD_TIMESTAMP=1412069902.0 -D__MBED__=1 -DTARGET_NRF51822 -DTARGET_FF_ARDUINO 

LD_FLAGS = -mcpu=cortex-m0 -mthumb -Wl,--gc-sections -Wl,--wrap=main --specs=nano.specs -u _printf_float -u _scanf_float
LD_SYS_LIBS = -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys

ifeq ($(DEBUG), 1)
  CC_FLAGS += -DDEBUG -O0
else
  CC_FLAGS += -DNDEBUG -Os
endif

all: $(PROJECT).hex 

clean:
	rm -f $(PROJECT).hex $(PROJECT).elf $(OBJECTS)

.s.o:
	$(AS) $(CPU) -o $@ $<

.c.o:
	$(CC)  $(CC_FLAGS) $(CC_SYMBOLS) -std=gnu99   $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	$(CPP) $(CC_FLAGS) $(CC_SYMBOLS) -std=gnu++98 $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS)
	$(LD) $(LD_FLAGS) -T$(LINKER_SCRIPT) $(LIBRARY_PATHS) -o $@ $^ $(LIBRARIES) $(LD_SYS_LIBS) $(LIBRARIES) $(LD_SYS_LIBS)

$(PROJECT).hex: $(PROJECT).elf
	$(OBJCOPY) -O ihex $< $@

merge:
	$(SREC_CAT) $(SOFTDEVICE) -intel $(PROJECT).hex -intel -o combined.hex -intel --line-length=44